### ISSUE TITLE
Improve Zettelkasten behaviour

### ISSUE THREAD

**Issue by cvigilv** [cvigilv/mateo.nvim#13]
# Tasks

- [ ] Add keymaps to handle links (create, remove, change, etc.)
- [ ] Implement sidebar with links _a la_ Obsidian
- [ ] Implement media inserter from clipboard
- [ ] Create cheatsheet with Obsidian Markdown flavor
- [ ] Add searcher for task tags
- [ ] Add searcher for tags and note types
