### ISSUE TITLE
New MiniStarter

### ISSUE THREAD

**Issue by cvigilv** [cvigilv/mateo.nvim#14]
Stopped using `MiniStarter` for `oil.nvim` + `telescope.nvim`, but want to go back to using the
first. This issue intends in changing my current `MiniStarter` config.

# Tasks

- [x] Remove sessions section
- [x] Add startuptime from lazy
  - `require("lazy").stats().startuptime`
- [x] Add number of packages loaded / lazy-loaded
- [x] Add number of packages available to update
- [x] Add cheatsheet section with useful keybinds

**Comment by cvigilv** [comment]
Close by #16
