### ISSUE TITLE
FEAT: Simplify statusline

### ISSUE THREAD

**Issue by cvigilv** [cvigilv/mateo.nvim#7]
# Tasks
Refer to [link](https://www.reddit.com/r/neovim/comments/10o64ke/can_someone_point_me_to_this_status_line_plugin/)

- [ ] Choose colors to use for statusline (maybe more colorscheme agnostic)
- [ ] Convert back to statusline per window
- [ ] Create function to switch from global to local statusline

**Comment by cvigilv** [comment]
Closing this issue since it would overlap with the issue I'll create that aims
to fix some problems that I currently have with my statusline.
